/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartyRouteImport } from './routes/party'
import { Route as PartyIndexRouteImport } from './routes/party.index'
import { Route as PartyPrintRouteImport } from './routes/party.print'
import { Route as ApiPublicItemIconIdRouteImport } from './routes/api/public/item-icon.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyRoute = PartyRouteImport.update({
  id: '/party',
  path: '/party',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyIndexRoute = PartyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartyRoute,
} as any)
const PartyPrintRoute = PartyPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => PartyRoute,
} as any)
const ApiPublicItemIconIdRoute = ApiPublicItemIconIdRouteImport.update({
  id: '/api/public/item-icon/$id',
  path: '/api/public/item-icon/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/party': typeof PartyRouteWithChildren
  '/party/print': typeof PartyPrintRoute
  '/party/': typeof PartyIndexRoute
  '/api/public/item-icon/$id': typeof ApiPublicItemIconIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/party/print': typeof PartyPrintRoute
  '/party': typeof PartyIndexRoute
  '/api/public/item-icon/$id': typeof ApiPublicItemIconIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/party': typeof PartyRouteWithChildren
  '/party/print': typeof PartyPrintRoute
  '/party/': typeof PartyIndexRoute
  '/api/public/item-icon/$id': typeof ApiPublicItemIconIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/party' | '/party/print' | '/party/' | '/api/public/item-icon/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/party/print' | '/party' | '/api/public/item-icon/$id'
  id:
    | '__root__'
    | '/'
    | '/party'
    | '/party/print'
    | '/party/'
    | '/api/public/item-icon/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PartyRoute: typeof PartyRouteWithChildren
  ApiPublicItemIconIdRoute: typeof ApiPublicItemIconIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party': {
      id: '/party'
      path: '/party'
      fullPath: '/party'
      preLoaderRoute: typeof PartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/': {
      id: '/party/'
      path: '/'
      fullPath: '/party/'
      preLoaderRoute: typeof PartyIndexRouteImport
      parentRoute: typeof PartyRoute
    }
    '/party/print': {
      id: '/party/print'
      path: '/print'
      fullPath: '/party/print'
      preLoaderRoute: typeof PartyPrintRouteImport
      parentRoute: typeof PartyRoute
    }
    '/api/public/item-icon/$id': {
      id: '/api/public/item-icon/$id'
      path: '/api/public/item-icon/$id'
      fullPath: '/api/public/item-icon/$id'
      preLoaderRoute: typeof ApiPublicItemIconIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PartyRouteChildren {
  PartyPrintRoute: typeof PartyPrintRoute
  PartyIndexRoute: typeof PartyIndexRoute
}

const PartyRouteChildren: PartyRouteChildren = {
  PartyPrintRoute: PartyPrintRoute,
  PartyIndexRoute: PartyIndexRoute,
}

const PartyRouteWithChildren = PartyRoute._addFileChildren(PartyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PartyRoute: PartyRouteWithChildren,
  ApiPublicItemIconIdRoute: ApiPublicItemIconIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
